version: "3.6"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "/redis.conf"]
